import type { DynamicStructuredTool } from "@langchain/core/tools";
import { suggestDestinationsTool } from "../suggest-destinations";
import { suggestFlightTool } from "../suggest-flight";
import { suggestHotelBookingTool } from "../suggest-hotel-booking";
import { suggestNewTripTool } from "../suggest-new-trip";

const SUPERVISOR_MCP_TOOLS = [
  "get_trip_details",
  "update_trip",
  "get_user_preferences",
  "get_weather",
] as const;

const DESTINATION_MCP_TOOLS = [
  "search_destinations",
  "get_destination_details",
  "get_recommended_destinations",
  "get_weather",
] as const;

const FLIGHT_MCP_TOOLS = [
  "search_flights",
  "create_flight_booking",
  "cancel_flight_booking",
  "get_trip_details",
  "get_weather",
] as const;

const HOTEL_MCP_TOOLS = [
  "search_hotels",
  "create_hotel_booking",
  "cancel_hotel_booking",
  "get_trip_details",
  "get_weather",
] as const;

const ITINERARY_MCP_TOOLS = [
  "search_places",
  "get_place_details",
  "create_itinerary",
  "add_itinerary_day",
  "add_itinerary_activity",
  "update_itinerary_activity",
  "delete_itinerary_activity",
  "get_weather",
] as const;

/**
 * Single source of truth for tool ownership across all TripLoom agents.
 */
const AGENT_TOOL_REGISTRY = {
  supervisor: {
    mcp: SUPERVISOR_MCP_TOOLS,
    local: [suggestNewTripTool] as const,
  },
  destination: {
    mcp: DESTINATION_MCP_TOOLS,
    local: [suggestDestinationsTool] as const,
  },
  flight: {
    mcp: FLIGHT_MCP_TOOLS,
    local: [suggestFlightTool] as const,
  },
  hotel: {
    mcp: HOTEL_MCP_TOOLS,
    local: [suggestHotelBookingTool] as const,
  },
  itinerary: {
    mcp: ITINERARY_MCP_TOOLS,
    local: [] as const,
  },
} as const;

type AgentRegistry = typeof AGENT_TOOL_REGISTRY;

export type AgentName = keyof AgentRegistry;
export type TripLoomMcpToolName = AgentRegistry[AgentName]["mcp"][number];

/**
 * MCP tools that require user approval before execution.
 * These are wrapped with `withApproval()` to interrupt for confirmation.
 *
 * To add approval to a new tool, just add its name here.
 */
const APPROVAL_REQUIRED_TOOL_NAMES = [
  "create_itinerary",
  "add_itinerary_day",
  "add_itinerary_activity",
  "update_itinerary_activity",
  "delete_itinerary_activity",
  "cancel_hotel_booking",
  "cancel_flight_booking",
] as const satisfies readonly TripLoomMcpToolName[];

export const APPROVAL_REQUIRED_TOOLS: ReadonlySet<string> = new Set(
  APPROVAL_REQUIRED_TOOL_NAMES,
);

export type TripLoomLocalTool = AgentRegistry[AgentName]["local"][number];
export type TripLoomLocalToolName = TripLoomLocalTool["name"];
export type TransferToolName = (typeof TRANSFER_TOOL_NAMES)[number];
export type TripLoomToolName =
  | TripLoomMcpToolName
  | TripLoomLocalToolName
  | TransferToolName;

const TRIP_LOOM_LOCAL_TOOL_NAMES = [
  suggestDestinationsTool.name,
  suggestFlightTool.name,
  suggestHotelBookingTool.name,
  suggestNewTripTool.name,
] as const;

/**
 * Transfer tools auto-generated by LangGraph's createSupervisor.
 * Must be included in the history allowlist so the API doesn't strip them.
 */
export const TRANSFER_TOOL_NAMES = [
  "transfer_to_destination_agent",
  "transfer_to_flight_agent",
  "transfer_to_hotel_agent",
  "transfer_to_itinerary_agent",
  "transfer_back_to_supervisor",
] as const;

export const TRIP_LOOM_TOOL_NAMES = [
  ...SUPERVISOR_MCP_TOOLS,
  ...DESTINATION_MCP_TOOLS,
  ...FLIGHT_MCP_TOOLS,
  ...HOTEL_MCP_TOOLS,
  ...ITINERARY_MCP_TOOLS,
  ...TRIP_LOOM_LOCAL_TOOL_NAMES,
  ...TRANSFER_TOOL_NAMES,
] as const;

function filterMcpTools(
  tools: DynamicStructuredTool[],
  names: readonly TripLoomMcpToolName[],
) {
  const nameSet = new Set<string>(names);
  return tools.filter((tool) => nameSet.has(tool.name));
}

export function getMcpToolsForAgent(
  allTools: DynamicStructuredTool[],
  agent: AgentName,
) {
  return filterMcpTools(allTools, AGENT_TOOL_REGISTRY[agent].mcp);
}

export function getLocalToolsForAgent(agent: AgentName) {
  return [...AGENT_TOOL_REGISTRY[agent].local];
}
