import type { Amenity } from "@trip-loom/contracts/enums";

export const amenityLabels: Record<Amenity, string> = {
  wifi: "Wi-Fi",
  "free-wifi": "Free Wi-Fi",
  pool: "Pool",
  "indoor-pool": "Indoor pool",
  "outdoor-pool": "Outdoor pool",
  "heated-pool": "Heated pool",
  "infinity-pool": "Infinity pool",
  "rooftop-pool": "Rooftop pool",
  spa: "Spa",
  sauna: "Sauna",
  "steam-room": "Steam room",
  "hot-tub": "Hot tub",
  gym: "Gym",
  "fitness-center": "Fitness center",
  restaurant: "Restaurant",
  bar: "Bar",
  "rooftop-bar": "Rooftop bar",
  "coffee-shop": "Coffee shop",
  parking: "Parking",
  "free-parking": "Free parking",
  "valet-parking": "Valet parking",
  "airport-shuttle": "Airport shuttle",
  "free-airport-transportation": "Free airport transportation",
  "room-service": "Room service",
  concierge: "Concierge",
  "beach-access": "Beach access",
  beachfront: "Beachfront",
  "private-beach": "Private beach",
  "pet-friendly": "Pet-friendly",
  "business-center": "Business center",
  "meeting-rooms": "Meeting rooms",
  "conference-facilities": "Conference facilities",
  "kids-club": "Kids’ club",
  "kids-pool": "Kids’ pool",
  laundry: "Laundry",
  "dry-cleaning": "Dry cleaning",
  "air-conditioning": "Air conditioning",
  balcony: "Balcony",
  "private-balcony": "Private balcony",
  "ocean-view": "Ocean view",
  "city-view": "City view",
  "mountain-view": "Mountain view",
  "24-hour-front-desk": "24-hour front desk",
  "24-hour-security": "24-hour security",
  "accessible-rooms": "Accessible rooms",
  "wheelchair-access": "Wheelchair access",
  "all-inclusive": "All-inclusive",
  babysitting: "Babysitting",
  "baggage-storage": "Baggage storage",
  bathrobes: "Bathrobes",
  "breakfast-included": "Breakfast included",
  "breakfast-buffet": "Breakfast buffet",
  casino: "Casino",
  "currency-exchange": "Currency exchange",
  doorperson: "Doorperson",
  "electric-vehicle-charging": "EV charging",
  "executive-lounge": "Executive lounge",
  "express-check-in": "Express check-in",
  "family-rooms": "Family rooms",
  fireplace: "Fireplace",
  "gift-shop": "Gift shop",
  "golf-course": "Golf course",
  "hair-dryer": "Hair dryer",
  housekeeping: "Housekeeping",
  kitchenette: "Kitchenette",
  minibar: "Minibar",
  "non-smoking-rooms": "Non-smoking rooms",
  "non-smoking-hotel": "Non-smoking hotel",
  "on-demand-movies": "On-demand movies",
  "outdoor-furniture": "Outdoor furniture",
  patio: "Patio",
  "private-bathroom": "Private bathroom",
  refrigerator: "Refrigerator",
  safe: "Safe",
  "shuttle-service": "Shuttle service",
  "soundproof-rooms": "Soundproof rooms",
  suites: "Suites",
  "sun-terrace": "Sun terrace",
  "tennis-court": "Tennis court",
  tv: "TV",
  "flatscreen-tv": "Flat-screen TV",
  "bicycle-rental": "Bicycle rental",
  diving: "Diving",
  snorkeling: "Snorkeling",
  "water-sports": "Water sports",
  hiking: "Hiking",
  "yoga-classes": "Yoga classes",
  massage: "Massage",
  "couples-massage": "Couples massage",
  "poolside-bar": "Poolside bar",
  "snack-bar": "Snack bar",
  "special-diet-menus": "Special diet menus",
  telephone: "Telephone",
  iron: "Iron",
};
