export const tripStatusValues = [
  "draft",
  "upcoming",
  "current",
  "past",
  "cancelled",
] as const;
export type TripStatus = (typeof tripStatusValues)[number];

export const flightTypeValues = ["outbound", "inbound"] as const;
export type FlightType = (typeof flightTypeValues)[number];

export const cabinClassValues = ["economy", "business", "first"] as const;
export type CabinClass = (typeof cabinClassValues)[number];

export const bookingStatusValues = ["pending", "confirmed", "cancelled"] as const;
export type BookingStatus = (typeof bookingStatusValues)[number];

export const priceRangeValues = ["budget", "moderate", "upscale", "luxury"] as const;
export type PriceRange = (typeof priceRangeValues)[number];

export const budgetRangeValues = priceRangeValues;
export type BudgetRange = PriceRange;

export const paymentStatusValues = [
  "pending",
  "processing",
  "succeeded",
  "failed",
  "refunded",
  "partially_refunded",
] as const;
export type PaymentStatus = (typeof paymentStatusValues)[number];

export const travelInterestValues = [
  "beaches",
  "culture",
  "food",
  "nightlife",
  "adventure",
  "history",
  "nature",
  "shopping",
  "relaxation",
  "architecture",
  "wildlife",
  "mountains",
  "islands",
  "temples",
  "art",
  "wine",
  "skiing",
  "diving",
  "hiking",
  "photography",
] as const;
export type TravelInterest = (typeof travelInterestValues)[number];

export const amenityValues = [
  "wifi",
  "free-wifi",
  "pool",
  "indoor-pool",
  "outdoor-pool",
  "heated-pool",
  "infinity-pool",
  "rooftop-pool",
  "spa",
  "sauna",
  "steam-room",
  "hot-tub",
  "gym",
  "fitness-center",
  "restaurant",
  "bar",
  "rooftop-bar",
  "coffee-shop",
  "parking",
  "free-parking",
  "valet-parking",
  "airport-shuttle",
  "free-airport-transportation",
  "room-service",
  "concierge",
  "beach-access",
  "beachfront",
  "private-beach",
  "pet-friendly",
  "business-center",
  "meeting-rooms",
  "conference-facilities",
  "kids-club",
  "kids-pool",
  "laundry",
  "dry-cleaning",
  "air-conditioning",
  "balcony",
  "private-balcony",
  "ocean-view",
  "city-view",
  "mountain-view",
  "24-hour-front-desk",
  "24-hour-security",
  "accessible-rooms",
  "wheelchair-access",
  "all-inclusive",
  "babysitting",
  "baggage-storage",
  "bathrobes",
  "breakfast-included",
  "breakfast-buffet",
  "casino",
  "currency-exchange",
  "doorperson",
  "electric-vehicle-charging",
  "executive-lounge",
  "express-check-in",
  "family-rooms",
  "fireplace",
  "gift-shop",
  "golf-course",
  "hair-dryer",
  "housekeeping",
  "kitchenette",
  "minibar",
  "non-smoking-rooms",
  "non-smoking-hotel",
  "on-demand-movies",
  "outdoor-furniture",
  "patio",
  "private-bathroom",
  "refrigerator",
  "safe",
  "shuttle-service",
  "soundproof-rooms",
  "suites",
  "sun-terrace",
  "tennis-court",
  "tv",
  "flatscreen-tv",
  "bicycle-rental",
  "diving",
  "snorkeling",
  "water-sports",
  "hiking",
  "yoga-classes",
  "massage",
  "couples-massage",
  "poolside-bar",
  "snack-bar",
  "special-diet-menus",
  "telephone",
  "iron",
] as const;
export type Amenity = (typeof amenityValues)[number];

export const regionValues = [
  "Europe",
  "East Asia",
  "Southeast Asia",
  "South Asia",
  "North America",
  "South America",
  "Central America",
  "Caribbean",
  "Middle East",
  "North Africa",
  "Sub-Saharan Africa",
  "Oceania",
  "Central Asia",
] as const;
export type Region = (typeof regionValues)[number];

export const hotelRoomTypeValues = [
  "standard",
  "deluxe",
  "suite",
  "junior-suite",
  "double",
  "twin",
  "single",
  "king",
  "queen",
  "family",
  "penthouse",
  "villa",
] as const;
export type HotelRoomType = (typeof hotelRoomTypeValues)[number];

export const hotelStyleValues = [
  "art-deco",
  "bay-view",
  "boutique",
  "budget",
  "business",
  "centrally-located",
  "charming",
  "city-view",
  "classic",
  "family",
  "family-resort",
  "great-view",
  "green",
  "harbor-view",
  "hidden-gem",
  "historic",
  "lagoon-view",
  "lake-view",
  "luxury",
  "marina-view",
  "mid-range",
  "modern",
  "mountain-view",
  "ocean-view",
  "park-view",
  "quaint",
  "quiet",
  "quirky",
  "residential",
  "river-view",
  "romantic",
  "trendy",
  "value",
] as const;
export type HotelStyle = (typeof hotelStyleValues)[number];
